In [1]:
import duckdb

In [2]:
# criando uma conexão
con = duckdb.connect(database = 'dados_duckdb.db', read_only = False)

In [3]:
# carregando os dados da tabela produtos
df = con.execute('select * from produtos').fetchdf()
df

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10003      PREGO         BT10            100      60.0
3  10004      SERRA         BT50            100     200.0
4  10005    MACHADO         BT50            100     100.0

In [5]:
# removendo duas colunas
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO    1500.0
2  10003      PREGO      60.0
3  10004      SERRA     200.0
4  10005    MACHADO     100.0

In [6]:
# criando uma nova tabela para gold
con.execute("""
    create table if not exists dim_produtos(
    id_prooduto bigint,
    nm_produto text,
    vl_produto float)
""")

In [8]:
# inserindo os dados na tabela
con.execute('insert into dim_produtos select * from df2')

In [9]:
# consultando os dados dentro de dim_produtos
df_dim = con.execute('select * from dim_produtos').fetchdf()
df_dim

   id_prooduto nm_produto  vl_produto
0        10001   PARAFUSO       100.0
1        10002    MARTELO      1500.0
2        10003      PREGO        60.0
3        10004      SERRA       200.0
4        10005    MACHADO       100.0

In [10]:
con.close()