In [5]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [6]:
# criando a conexão com o banco
con = duckdb.connect(database = 'dados_duckdb.db', read_only = False)

In [12]:
# carregando os dados
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep = ";")
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao

In [13]:
df

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10003    PREGO  BT10    100     60  z0019_2.csv 2026-05-31 16:18:53.878480
1  10004    SERRA  BT50    100    200  z0019_2.csv 2026-05-31 16:18:53.878480
2  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-05-31 16:18:53.878480

In [9]:
# criando a tabela bronze
con.execute("""
    create table if not exists bronze_z0019(
    NATBR varchar,
    MAKTX varchar,
    WERKS varchar,
    MAINS varchar,
    LABST varchar,
    nome_arquivo varchar,
    data_ingestao timestamp
    )
""")

In [14]:
# inserindo os dados do df para a tabela bronze_produtos
con.execute('insert into bronze_z0019 select * from df')

In [15]:
# visualizando o resultado da tabela bronze_produtos
resultado = con.execute('select * from bronze_z0019').fetchdf()
resultado

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-05-31 16:18:14.562467
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-05-31 16:18:14.562467
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-05-31 16:18:14.562467
3  10003     PREGO  BT10   100    60  z0019_2.csv 2026-05-31 16:18:53.878480
4  10004     SERRA  BT50   100   200  z0019_2.csv 2026-05-31 16:18:53.878480
5  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-05-31 16:18:53.878480

In [ ]:
#con.execute('alter table bronze_produtos rename to bronze_z0019')

In [16]:
# fechando a conexão
con.close()